# 11th  to 15th EXPERIMENT :

In [11]:
#11th EXPERIMENT:

def star(n):
    
    for i in range(0, n):
     
        for j in range(0, i+1):
         
            print("*",end="")
            
        print("\r")
n = 5
star(n)

*
**
***
****
*****


In [12]:
#12th EXPERMENT:

string = input("enter a string: ")
i = int(input("enter no of char to be removed: "))
new_string =string.replace(string[0:i],"")
print(new_string)

enter a string: bhjgsagh
enter no of char to be removed: 2
jgsagh


In [21]:
#13th EXPERMENT:

input_string = input('Enter elements: ')
list1 = input_string.split()
for i in range(len(list1)):
    list1[i] = int(list1[i])
    if list1[i]%5==0:
        print(list1[i],end=" ")


Enter elements: 1


In [24]:
#14th EXPERMENT:

strg="Hi HiihihiHihiHihihi"
sub="Hi"

print("No. of times substring appears :",strg.count(sub))

No. of times substring appears : 4


In [1]:
#15th EXPERMENT:

def numbers(n):
    
    for i in range(1, n):
     
        for j in range(1, i+1):
         
            print(i,end="")
            
        print("\r")
n = 6
numbers(n)

1
22
333
4444
55555


# TUPLES:



### 1st Experiment:
 ##### Python program to Find the size of a Tuple:

In [42]:


Tuple1 = ("E","W","Z", 54,79,100)
Tuple2 = ("Anjay", "Wesly", "Sadha", "Nikhil", "Rajesh", "venkat")
Tuple3 = ((78, "Roar"), ( 2, "King"), (100, "Last"), (65, "Rock"),( 7, "Feast"))

print("Size of Tuple1: " + str(Tuple1.__sizeof__()) + "bytes")
print("Size of Tuple2: " + str(Tuple2.__sizeof__()) + "bytes")
print("Size of Tuple3: " + str(Tuple3.__sizeof__()) + "bytes")


Size of Tuple1: 72bytes
Size of Tuple2: 72bytes
Size of Tuple3: 64bytes


## 2nd Experiment:
### Python – Maximum and Minimum K elements in Tuple:

In [30]:
my_tuple = (20, 755, 556, 10, 60, 78)
print("The tuple is : ")
print(my_tuple)
K = 1
print("The value of K has been initialized to ")
print(K)
my_result = []
my_tuple = list(my_tuple)
temp = sorted(my_tuple)
for idx, val in enumerate(temp):
    if idx < K or idx >= len(temp) - K:
         my_result.append(val)
my_result = tuple(my_result)
print("The result is : " )
print(my_result)


The tuple is : 
(20, 755, 556, 10, 60, 78)
The value of K has been initialized to 
1
The result is : 
(10, 755)


## 3rd Experiment:
### Python – Sum of tuple elements:

In [44]:
numTuple = (20, 40, 65, 75, 80, 220)
print("Tuple Items = ", numTuple)

tupleSum = sum(numTuple)
print("\nThe Sum of numTuple Tuple Items = ", tupleSum)

Tuple Items =  (20, 40, 65, 75, 80, 220)

The Sum of numTuple Tuple Items =  500


# SET:


## 1st Experiment
### Find the size of a Set in Python:

In [45]:
set1 = {"E","W","Z", 54,79,100}
set2 = {"Anjay", "Wesly", "Sadha", "Nikhil", "Rajesh", "venkat"}
set3 = {(78, "Roar"), ( 2, "King"), (100, "Last"), (65, "Rock"),( 7, "Feast")}

print("Size of set1: " + str(set1.__sizeof__()) + "bytes")
print("Size of set2: " + str(set2.__sizeof__()) + "bytes")
print("Size of set3: " + str(set3.__sizeof__()) + "bytes")


Size of set1: 456bytes
Size of set2: 456bytes
Size of set3: 456bytes


## 2nd Experiment
### Iterate over a set in Python:

In [46]:
iterate = set("ShAstEesWaran")

for val in iterate:
    print(val)


e
n
E
W
r
A
a
s
S
t
h


# MATRIX:

## 1st Experiment:
### Assigning Subsequent Rows to Matrix first row elements:

In [34]:
my_list=[[1,3,5],[2,4,6],[7,9,11],[10,20,30]]
print("my list :"+str(my_list))
result={my_list[0][val] : my_list[val+1] for val in range(len(my_list)-1)}
print("The matrix : " +str(result))

my list :[[1, 3, 5], [2, 4, 6], [7, 9, 11], [10, 20, 30]]
The matrix : {1: [2, 4, 6], 3: [7, 9, 11], 5: [10, 20, 30]}


## 2nd Experiment:
### Adding and Subtracting Matrices in Python:

In [33]:
import numpy as np
A = np.array([[2,6],[5,6]])
B = np.array([[2,2],[6,8]])
print("elments in A")
print(A)
print("elments in B")
print(B)
print("addition of two matrix")
print(np.add(A,B))
print("subtraction of two matrics")
print(np.subtract(A,B))

elments in A
[[2 6]
 [5 6]]
elments in B
[[2 2]
 [6 8]]
addition of two matrix
[[ 4  8]
 [11 14]]
subtraction of two matrics
[[ 0  4]
 [-1 -2]]


# Function:

## 1st Experiment:
### How to get list of parameters name from a function in Python:

In [38]:
def function(a, b,c,d):
    return a**b**c**d
import inspect
print(inspect.signature(function9))

(a, b, c, d)


## 2nd Experiment:
### How to Print Multiple Arguments in Python:

In [41]:
def student(student_name,dob):
     print("STUDENT DETAILS : " , student_name + ',' + dob)
student("Wills Smith" , "24/02/2000")
student("James" , "18/09/2006")
student("Anderson" , "19/08/2005")

STUDENT DETAILS :  Wills Smith,24/02/2000
STUDENT DETAILS :  James,18/09/2006
STUDENT DETAILS :  Anderson,19/08/2005


# DICTIONARY:

## 1st Experiment:
### Sort Python Dictionaries by Key or Value:

In [46]:
a={10:'Carrot',20:'Beans',50:'Potato',80:'Chilly'}
a=dict(sorted(a.items()))
print(a)

{10: 'Carrot', 20: 'Beans', 50: 'Potato', 80: 'Chilly'}


## 2nd Experiment:
### Python dictionary with keys having multiple inputs:

In [50]:
dict1 = {}
a, b, c = 20, 69, 66
dict1[a, b, c] = a + b - c

a, b, c = 10, 68, 60
dict1[a, b, c] = a + b - c

print("The dictionary is :")
print(dict1)

The dictionary is :
{(20, 69, 66): 23, (10, 68, 60): 18}


# STRING:

## 1st Experiment:
### Python program to check whether the string is Symmetrical or Palindrome:

In [51]:
string=input("Enter a string :")
rev=string[::-1]

if string==rev:
    print("It is palindrome")
else:
    print("It is not a palindrome")


Enter a string :MALAYALAM
It is palindrome


## 2nd Experiment:
### Reverse words in a given String in Python:

In [53]:
string="SHASTEESWARAN"
new=''
for i in string.split():
    new+=i[::-1]+' '
    
print(new)

NARAWSEETSAHS 


## 3rd Experiment:
### Ways to remove i’th character from string in Python:

In [62]:
str1 = "helloishello"
print ("The original string is : " + str1)
z = str(input("Which character you want to remove ?"))
new = str1.replace(z, '', 1)
print ("The string after removal of i'th character(works) : " + new)

The original string is : helloishello
Which character you want to remove ?l
The string after removal of i'th character(works) : heloishello


# LIST:

## 1st Experiment:
### Python program to interchange first and last elements in a list:

In [64]:
l=[]
length=int(input("Enter list size :"))
for i in range(0,length):
    e=int(input("Enter element :"))
    l.append(e)

l[0],l[length-1]=l[length-1],l[0]
print(l)

Enter list size :2
Enter element :1
Enter element :2
[2, 1]


## 2nd Experiment:
### Python program to swap two elements in a list:

In [66]:
a=[10,100]
a[0],a[len(a)-1]=a[len(a)-1],a[0]
print(l)

[100, 10]


## 3rd Experiment:
### Ways to find length of list:

In [68]:
s=[34,40,50,66]
count=0
for i in s:
    count+=1   
print("Length of list :",count)

Length of list : 4


## 4th Experiment:
### Maximum of two numbers in Python:

In [73]:
def maximum(a, b):

    if a >= b:
        return a
    else:
        return b

a = 10
b = 50
print(maximum(a, b))


4


## 5th Experiment:
### Minimum of two numbers in Python:

In [74]:
def minimum(a, b):

    if a >= b:
        return a
    else:
        return b

a = 10
b = 50
print(minimum(a, b))


50
